<!DOCTYPE html>
<html>
<?php include_once("header.php");?>
<link rel="stylesheet" type="text/css" href="Style.CSS">

<head>
	<title>Borah High School Wrestling</title>
	<link rel="stylesheet" href="Style.CSS">
	<link rel="icon" href="Logo.jpg" type="image/gif" sizes="16x16">
</head>
<h1>
	<img src="transparent.png" alt="Borah Wrestler" height="25%" width="25%">
</h1>
<div >
<ul>
	<li><a href ="Home.PHP">Home</a></li>
	<li><a href ="https://www.sierratradingpost.com/">Schedule</a></li>
	<li><a href ="https://www.sportsmanswarehouse.com/">Wrestler Login</a></li>
	<li><a href ="https://www.cabelas.com/">Fundraising</a></li>
	<li><a href ="https://www.basspro.com/">Spirit Gear</a></li>
	<li><a href ="http://vortexoptics.com/">Photos</a></li>
	<li><a href ="https://www.nikon.com/">Coaching Staff</a></li>
</ul>
</div>

<body>
<p>Welcome to Borah High School's wrestling page. This page contains all information needed for wrestlers, parents, fans, and administrators. We cannot thank you enough for your support and look forward to seeing you at our next match.
<img src="Alias.jpg" alt="Borah Wrestler" height="25%" width="25%" class="center">
</p>
</body>
</html>

