<!DOCTYPE html>
<html>
<?php require_once "header.php"; ?>

<body>
<br>
<p>Welcome to Borah High School's wrestling page. This page contains all information needed for wrestlers, parents, fans, and administrators. We cannot thank you enough for your support and look forward to seeing you at our next match.</p>
<img src="Alias.jpg" alt="Borah Wrestler" height="50" width="50">
</body>
<br>

</html>

